version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: local.DockerFile
    container_name: code-runner-api-local
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      APP_ENVIRONMENT: local
      HOST_TEMP_DIR: ${PWD}/temp_code_files
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./temp_code_files:/tmp/runbox
    depends_on:
      - postgres
    networks:
      - app_net

  postgres:
    image: postgres:16
    container_name: code-runner-db-local
    environment:
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: code_runner_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_net

volumes:
  postgres_data:

networks:
  app_net:
    driver: bridge