version: '3.8'

services:
  api:
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 8G
    build:
      context: .
      dockerfile: local.DockerFile
    container_name: code-runner-api-local
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      APP_ENVIRONMENT: local
      HOST_TEMP_DIR: ${PWD}/temp_code_files
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./temp_code_files:/tmp/runbox
    depends_on:
      - postgres
      - redis
    networks:
      - app_net

  postgres:
    image: postgres:16
    container_name: code-runner-db-local
    environment:
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: code_runner_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_net

  redis:
    image: redis:latest
    container_name: code-runner-redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_net

volumes:
  postgres_data:
  redis_data:

networks:
  app_net:
    driver: bridge
